#include <furi.h>
#include <furi_hal.h>

#include <furi_hal_gpio.h>
#include <furi_hal_resources.h>

#include <gui/gui.h>
#include <locale/locale.h>

#include <gui/scene_manager.h>
#include <gui/view_dispatcher.h>
// GUI Modules
#include <gui/modules/text_box.h>
#include <gui/modules/widget.h>
#include <gui/modules/submenu.h>
#include <gui/modules/text_input.h>

// My modules
#include "cross_flipper_communication.h"
/* generated by fbt from .png files in images folder */
#include <cross_flipper_communication_icons.h>
// Frequency's
int frequenciesSize = 8;
float frequencies[] =
    {446.00625, 446.01875, 446.03125, 446.04375, 446.05625, 446.06875, 446.08125, 446.09375};

// Scenes
typedef enum {
    AppSceneSelectMode,
    AppSceneSubGHzSelectFrequency,
    AppSceneSubGhzSelectMode,
    AppSceneSubGhzChatLog,
    AppSceneSubGHzChatBox,
    AppSceneNum
} appScene;
// Views
typedef enum { AppViewTextbox, AppViewWidget, AppViewSubmenu, AppViewTextInput } appViews;

// Custom Event Enums
typedef enum {
    AppSubGHzSelectFrequency,
    AppSelectModeSubGhz,
    AppSubGHzSelectModeChatLog,
    AppSubGHzSelectModeWriteMessage
} AppCustomEvents;

// Menu Callbacks
void app_callbacks_select_mode_menu(void* context, uint32_t index) {
    App* app = context;
    switch(index) {
    case AppSelectModeSubGhz:
        scene_manager_handle_custom_event(app->scene_manager, AppSelectModeSubGhz);
    };
};
void app_callbacks_subghz_select_frequency_menu(void* context, uint32_t index) {
    App* app = context;
    app->frequency = frequencies[index];
    scene_manager_handle_custom_event(app->scene_manager, AppSubGHzSelectFrequency);
}
void app_callbacks_subghz_select_mode_menu(void* context, uint32_t index) {
    App* app = context;
    if(index == 0) {
        scene_manager_handle_custom_event(app->scene_manager, AppSubGHzSelectModeChatLog);
    } else if(index == 1) {
        scene_manager_handle_custom_event(app->scene_manager, AppSubGHzSelectModeWriteMessage);
    }
}
// Scene Callbacks
void app_scene_select_mode_on_enter(void* context) {
    App* app = context;
    Submenu* submenu = app->submenu;
    submenu_reset(submenu);
    submenu_set_header(submenu, "Select Mode");
    submenu_add_item(submenu, "SubGHz", AppSelectModeSubGhz, app_callbacks_select_mode_menu, app);
    view_dispatcher_switch_to_view(app->view_dispatcher, AppViewSubmenu);
}
bool app_scene_select_mode_on_event(void* context, SceneManagerEvent event) {
    App* app = context;
    bool consumed = false;
    if(event.type == SceneManagerEventTypeCustom) {
        consumed = true;
        if(event.event == AppSelectModeSubGhz) {
            scene_manager_next_scene(app->scene_manager, AppSceneSubGHzSelectFrequency);
        }
    }
    return consumed;
};
void app_scene_select_mode_on_exit(void* context) {
    App* app = (App*)context;
    Submenu* submenu = app->submenu;
    submenu_reset(submenu);
};

void app_scene_subghz_select_frequency_on_enter(void* context) {
    App* app = context;
    Submenu* submenu = app->submenu;
    submenu_reset(submenu);
    submenu_set_header(submenu, "Select Frequency");
    for(int i = 0; i < frequenciesSize; i++) {
        FuriString* label = furi_string_alloc();
        furi_string_cat_printf(label, "Channel %d (%f)", i + 1, (double)frequencies[i]);
        submenu_add_item(
            app->submenu,
            furi_string_get_cstr(label),
            i,
            app_callbacks_subghz_select_frequency_menu,
            app);
    }
    view_dispatcher_switch_to_view(app->view_dispatcher, AppViewSubmenu);
};
bool app_scene_subghz_select_frequency_on_event(void* context, SceneManagerEvent event) {
    App* app = context;
    bool consumed = false;
    if(event.type == SceneManagerEventTypeCustom) {
        consumed = true;
        scene_manager_next_scene(app->scene_manager, AppSceneSubGhzSelectMode);
    }
    return consumed;
};
void app_scene_subghz_select_frequency_on_exit(void* context) {
    App* app = (App*)context;
    Submenu* submenu = app->submenu;
    submenu_reset(submenu);
};

void app_scene_subghz_select_mode_on_enter(void* context) {
    App* app = context;
    Submenu* submenu = app->submenu;
    submenu_reset(submenu);
    submenu_set_header(submenu, "Select Mode");
    submenu_add_item(submenu, "Read Chat", 0, app_callbacks_subghz_select_mode_menu, app);
    submenu_add_item(submenu, "Write A Message", 1, app_callbacks_subghz_select_mode_menu, app);
    view_dispatcher_switch_to_view(app->view_dispatcher, AppViewSubmenu);
}

bool app_scene_subghz_select_mode_on_event(void* context, SceneManagerEvent event) {
    App* app = context;
    bool consumed = false;
    if(event.type == SceneManagerEventTypeCustom) {
        consumed = true;
        if(event.event == AppSubGHzSelectModeChatLog) {
            scene_manager_next_scene(app->scene_manager, AppSceneSubGhzChatLog);
        } else if(event.event == AppSubGHzSelectModeWriteMessage) {
            scene_manager_next_scene(app->scene_manager, AppSceneSubGHzChatBox);
        }
    }
    return consumed;
}

void app_scene_subghz_select_mode_on_exit(void* context) {
    App* app = (App*)context;
    Submenu* submenu = app->submenu;
    submenu_reset(submenu);
}
// Handler Callback Lists
void (*const app_on_enter_handlers[])(void*) = {
    app_scene_select_mode_on_enter,
    app_scene_subghz_select_frequency_on_enter,
    app_scene_subghz_select_mode_on_enter,
};
bool (*const app_on_event_handlers[])(void* context, SceneManagerEvent event) = {
    app_scene_select_mode_on_event,
    app_scene_subghz_select_frequency_on_event,
    app_scene_subghz_select_mode_on_event,
};
void (*const app_on_exit_handlers[])(void* context) = {
    app_scene_select_mode_on_exit,
    app_scene_subghz_select_frequency_on_exit,
    app_scene_subghz_select_mode_on_exit,
};
const SceneManagerHandlers app_scene_handlers = {
    .on_enter_handlers = app_on_enter_handlers,
    .on_event_handlers = app_on_event_handlers,
    .on_exit_handlers = app_on_exit_handlers,
    .scene_num = AppSceneNum,
};

// View Dispatcher Callbacks
bool app_scene_custom_callback(void* context, uint32_t custom_event_id) {
    App* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event_id);
};
bool app_back_event_callback(void* context) {
    App* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}
// APP

App* app_alloc() {
    App* app = malloc(sizeof(App));
    app->frequency = 0;

    app->scene_manager = scene_manager_alloc(&app_scene_handlers, app);

    // View Dispatcher
    app->view_dispatcher = view_dispatcher_alloc();
    view_dispatcher_enable_queue(app->view_dispatcher);
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(app->view_dispatcher, app_scene_custom_callback);
    view_dispatcher_set_navigation_event_callback(app->view_dispatcher, app_back_event_callback);
    // TextBox
    app->text_box = text_box_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, AppViewTextbox, text_box_get_view(app->text_box));
    // Widget
    app->widget = widget_alloc();
    view_dispatcher_add_view(app->view_dispatcher, AppViewWidget, widget_get_view(app->widget));
    // Submenu
    app->submenu = submenu_alloc();
    view_dispatcher_add_view(app->view_dispatcher, AppViewSubmenu, submenu_get_view(app->submenu));
    // TextInput
    app->text_input = text_input_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, AppViewTextInput, text_input_get_view(app->text_input));
    return app;
};
void app_free(App* app) {
    view_dispatcher_remove_view(app->view_dispatcher, AppViewWidget);
    widget_free(app->widget);
    view_dispatcher_remove_view(app->view_dispatcher, AppViewTextbox);
    text_box_free(app->text_box);
    view_dispatcher_remove_view(app->view_dispatcher, AppViewSubmenu);
    submenu_free(app->submenu);
    view_dispatcher_remove_view(app->view_dispatcher, AppViewTextInput);
    text_input_free(app->text_input);
    view_dispatcher_free(app->view_dispatcher);
    scene_manager_free(app->scene_manager);
    free(app);
};

int32_t cross_flipper_communication_app(void* p) {
    UNUSED(p);

    App* app = app_alloc();
    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, AppSceneSelectMode);
    view_dispatcher_run(app->view_dispatcher);
    app_free(app);
    furi_record_close(RECORD_GUI);
    return 0;
};
