#include <furi.h>
#include <furi_hal.h>

#include <furi_hal_gpio.h>
#include <furi_hal_resources.h>

#include <gui/gui.h>
#include <locale/locale.h>

#include <gui/scene_manager.h>
#include <gui/view_dispatcher.h>

// GUI Modules
#include <gui/modules/text_box.h>
#include <gui/modules/widget.h>
#include <gui/modules/submenu.h>

/* generated by fbt from .png files in images folder */
#include <cross_flipper_communication_icons.h>
// KNOB
typedef enum {
    KnobEventDone,
} KnobCustomEvents;

typedef void (*KnobCallback)(void* context, uint32_t index);

typedef struct Knob {
    View* view;
} Knob;

typedef struct KnobModel {
    FuriString* buffer;
    uint16_t counter;
    char* heading;
    KnobCallback callback;
    void* callback_context;
} KnobModel;

// Set a callback to invoke when knob has an event.
// @knob is a pointer to our Knob instance.
// @callback is a function to invoke when we have custom events.
static void knob_set_callback(Knob* knob, KnobCallback callback, void* callback_context) {
    with_view_model(
        knob->view,
        KnobModel * model,
        {
            model->callback_context = callback_context;
            model->callback = callback;
        },
        true);
}

// Invoked when input (button press) is detected.
// @input_even is the event the occured.
// @ctx is a pointer to our Knob instance.
static bool knob_input_callback(InputEvent* input_event, void* ctx) {
    Knob* knob = (Knob*)ctx;

    bool handled = false;

    if(input_event->type == InputTypePress && input_event->key == InputKeyUp) {
        bool updated = false;
        with_view_model(
            knob->view,
            KnobModel * model,
            {
                if(model->counter) {
                    model->counter--;
                    updated = true;
                }
            },
            updated);
        handled = true;
    } else if(input_event->type == InputTypePress && input_event->key == InputKeyDown) {
        with_view_model(
            knob->view,
            KnobModel * model,
            { model->counter++; },
            true); // Render new data.
        handled = true;
    } else if(input_event->type == InputTypePress && input_event->key == InputKeyOk) {
        with_view_model(
            knob->view,
            KnobModel * model,
            {
                if(model->callback) {
                    model->callback(model->callback_context, KnobEventDone);
                } else {
                }
            },
            false); // No new data.
        handled = true;
    }

    return handled;
}

// Invoked by the draw callback to render the knob.
// @canvas is the canvas to draw on.
// @ctx is our model.
static void knob_render_callback(Canvas* canvas, void* ctx) {
    KnobModel* model = ctx;

    furi_string_printf(model->buffer, "Knob demo %d", model->counter);

    canvas_set_font(canvas, FontPrimary);

    if(model->heading) {
        canvas_draw_str_aligned(canvas, 64, 5, AlignCenter, AlignTop, model->heading);
    }

    canvas_draw_str_aligned(
        canvas, 15, 30, AlignLeft, AlignTop, furi_string_get_cstr(model->buffer));
}

// Allocates a Knob instance.
Knob* knob_alloc() {
    Knob* knob = malloc(sizeof(Knob));
    knob->view = view_alloc();

    // context passed to input_callback.
    view_set_context(knob->view, knob);

    // context passed to render.
    view_allocate_model(knob->view, ViewModelTypeLockFree, sizeof(KnobModel));
    with_view_model(
        knob->view,
        KnobModel * model,
        {
            model->buffer = furi_string_alloc();
            model->counter = 0;
            model->heading = NULL;
        },
        true);

    view_set_draw_callback(knob->view, knob_render_callback);
    view_set_input_callback(knob->view, knob_input_callback);
    return knob;
}
void knob_free(Knob* knob) {
    furi_assert(knob);
    with_view_model(
        knob->view, KnobModel * model, { furi_string_free(model->buffer); }, true);
    view_free(knob->view);
    free(knob);
}
View* knob_get_view(Knob* knob) {
    furi_assert(knob);
    return knob->view;
}
uint32_t knob_get_counter(Knob* knob) {
    furi_assert(knob);

    uint32_t value = 0;
    with_view_model(
        knob->view, KnobModel * model, { value = model->counter; }, false);

    return value;
}
void knob_set_counter(Knob* knob, float count) {
    with_view_model(
        knob->view, KnobModel * model, { model->counter = count; }, true);
}
void knob_set_heading(Knob* knob, char* heading) {
    with_view_model(
        knob->view, KnobModel * model, { model->heading = heading; }, true);
}

// Scenes
typedef struct App {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    TextBox* text_box;
    Widget* widget;
    Submenu* submenu;
    Knob* knob;
    float frequency;
} App;

typedef enum {
    AppSceneSelectMode,
    AppSceneSubGHzSelectFrequency,
    AppSceneSubGhzChatSelectMode,
    AppSceneSubGhzChatLog,
    AppSceneSubGHzChatBox,
    AppSceneNum
} appScene;

// Views
typedef enum { AppViewTextbox, AppViewWidget, AppViewSubmenu, AppViewKnob } appViews;

// Custom Event Enums
typedef enum {
    AppSubGHzSelectFrequencyKnob,
    AppSelectModeSubGhz,
} AppCustomEvents;

// Menu Callbacks
void app_callbacks_select_mode_menu(void* context, uint32_t index) {
    App* app = context;
    switch(index) {
    case AppSelectModeSubGhz:
        scene_manager_handle_custom_event(app->scene_manager, AppSelectModeSubGhz);
    };
};
void app_knob_callback(void* context, uint32_t index) {
    App* app = context;
    if(index == AppSubGHzSelectFrequencyKnob) {
        view_dispatcher_send_custom_event(app->view_dispatcher, AppSubGHzSelectFrequencyKnob);
    }
}
// Scene Callbacks
void app_scene_select_mode_on_enter(void* context) {
    App* app = context;
    Submenu* submenu = app->submenu;
    submenu_reset(submenu);
    submenu_set_header(submenu, "Select Mode");
    submenu_add_item(submenu, "SubGHz", AppSelectModeSubGhz, app_callbacks_select_mode_menu, app);
    view_dispatcher_switch_to_view(app->view_dispatcher, AppViewSubmenu);
}
bool app_scene_select_mode_on_event(void* context, SceneManagerEvent event) {
    App* app = context;
    bool consumed = false;
    if(event.type == SceneManagerEventTypeCustom) {
        consumed = true;
        if(event.event == AppSelectModeSubGhz) {
            scene_manager_next_scene(app->scene_manager, AppSceneSubGHzSelectFrequency);
        }
    }
    return consumed;
};
void app_scene_select_mode_on_exit(void* context) {
    App* app = (App*)context;
    Submenu* submenu = app->submenu;
    submenu_reset(submenu);
};

void app_scene_subghz_select_frequency_on_enter(void* context) {
    App* app = context;
    Knob* knob = app->knob;
    knob_set_callback(knob, AppSubGHzSelectFrequencyKnob, app);
    knob_set_heading(knob, "Frequency");
    knob_set_counter(knob, (float)app->frequency);
    view_dispatcher_switch_to_view(app->view_dispatcher, AppViewKnob);
};
bool app_scene_subghz_select_frequency_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false;
};
void app_scene_subghz_select_frequency_on_exit(void* context) {
    UNUSED(context);
};

// Handler Callback Lists
void (*const app_on_enter_handlers[])(void*) = {
    app_scene_select_mode_on_enter,
    app_scene_subghz_select_frequency_on_enter,
};
bool (*const app_on_event_handlers[])(void* context, SceneManagerEvent event) = {
    app_scene_select_mode_on_event,
    app_scene_subghz_select_frequency_on_event,
};
void (*const app_on_exit_handlers[])(void* context) = {
    app_scene_select_mode_on_exit,
    app_scene_subghz_select_frequency_on_exit,
};
const SceneManagerHandlers app_scene_handlers = {
    .on_enter_handlers = app_on_enter_handlers,
    .on_event_handlers = app_on_event_handlers,
    .on_exit_handlers = app_on_exit_handlers,
    .scene_num = AppSceneNum,
};

// View Dispatcher Callbacks
bool app_scene_custom_callback(void* context, uint32_t custom_event_id) {
    App* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event_id);
};
bool app_back_event_callback(void* context) {
    App* app = context;
    ;
    return scene_manager_handle_back_event(app->scene_manager);
}
// APP

App* app_alloc() {
    App* app = malloc(sizeof(App));
    app->frequency = 446.09375;

    app->scene_manager = scene_manager_alloc(&app_scene_handlers, app);

    // View Dispatcher
    app->view_dispatcher = view_dispatcher_alloc();
    view_dispatcher_enable_queue(app->view_dispatcher);
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(app->view_dispatcher, app_scene_custom_callback);
    view_dispatcher_set_navigation_event_callback(app->view_dispatcher, app_back_event_callback);
    // TextBox
    app->text_box = text_box_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, AppViewTextbox, text_box_get_view(app->text_box));
    // Widget
    app->widget = widget_alloc();
    view_dispatcher_add_view(app->view_dispatcher, AppViewWidget, widget_get_view(app->widget));
    // Submenu
    app->submenu = submenu_alloc();
    view_dispatcher_add_view(app->view_dispatcher, AppViewSubmenu, submenu_get_view(app->submenu));
    // Knob
    app->knob = knob_alloc();
    view_dispatcher_add_view(app->view_dispatcher, AppViewKnob, knob_get_view(app->knob));
    return app;
};
void app_free(App* app) {
    view_dispatcher_remove_view(app->view_dispatcher, AppViewWidget);
    widget_free(app->widget);
    view_dispatcher_remove_view(app->view_dispatcher, AppViewTextbox);
    text_box_free(app->text_box);
    view_dispatcher_remove_view(app->view_dispatcher, AppViewSubmenu);
    submenu_free(app->submenu);
    view_dispatcher_remove_view(app->view_dispatcher, AppViewKnob);
    knob_free(app->knob);
    view_dispatcher_free(app->view_dispatcher);
    scene_manager_free(app->scene_manager);
    free(app);
};

int32_t cross_flipper_communication_app(void* p) {
    UNUSED(p);
    App* app = app_alloc();
    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, AppSceneSelectMode);
    view_dispatcher_run(app->view_dispatcher);

    app_free(app);
    furi_record_close(RECORD_GUI);
    return 0;
};
