#include <furi.h>
#include <furi_hal.h>

#include <furi_hal_gpio.h>
#include <furi_hal_resources.h>

#include <gui/gui.h>
#include <locale/locale.h>

#include <gui/scene_manager.h>
#include <gui/view_dispatcher.h>

// GUI Modules
#include <gui/modules/text_box.h>
#include <gui/modules/widget.h>
/* generated by fbt from .png files in images folder */
#include <cross_flipper_communication_icons.h>

// Scenes
typedef struct App {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    TextBox* text_box;
    Widget* widget;
    float frequency;
} App;

typedef enum {
    AppSceneSelectMode,
    AppSceneSubGHzSelectFrequency,
    AppSceneSubGhzChatSelectMode,
    AppSceneSubGhzChatLog,
    AppSceneSubGHzChatBox,
    AppSceneNum
} appScene;

// Views
typedef enum {
    AppViewButton,
    AppViewTextbox,
    AppViewWidget,
} appViews;

// Custom Event Enums
typedef enum {
    AppKnobEventDone,
    AppWidgetEventDone,
} AppCustomEvents;

// Button Callbacks
void app_scene_select_mode_button_callback(GuiButtonType result, InputType type, void* ctx) {
    App* app = (App*)ctx;
    UNUSED(type);
    if(result == GuiButtonTypeCenter) {
        view_dispatcher_send_custom_event(app->view_dispatcher, AppWidgetEventDone);
    }
};

// Scene Callbacks
void app_scene_select_mode_on_enter(void* context) {
    App* app = context;
    Widget* widget = app->widget;
    widget_reset(widget);
    widget_add_text_scroll_element(widget, 20, 10, 80, 30, "This is a Placeholder.");
    widget_add_button_element(
        widget, GuiButtonTypeCenter, "OK", app_scene_select_mode_button_callback, app);
    view_dispatcher_switch_to_view(app->view_dispatcher, AppViewWidget);
};
bool app_scene_select_mode_on_event(void* context, SceneManagerEvent event) {
    App* app = context;
    bool consumed = false;
    if(event.type == SceneManagerEventTypeCustom) {
        consumed = true;
        if(event.event == AppWidgetEventDone) {
            scene_manager_next_scene(app->scene_manager, AppSceneSubGHzSelectFrequency);
        }
    }
    return consumed;
};
void app_scene_select_mode_on_exit(void* context) {
    App* app = (App*)context;
    Widget* widget = app->widget;
    widget_reset(widget);
};

void app_scene_subghz_select_frequency_on_enter(void* context) {
    App* app = context;
    Widget* widget = app->widget;
    widget_reset(widget);
    widget_add_text_scroll_element(widget, 20, 10, 80, 30, "This is a Place Holder. PG2");
    view_dispatcher_switch_to_view(app->view_dispatcher, AppViewWidget);
};
bool app_scene_subghz_select_frequency_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false;
};
void app_scene_subghz_select_frequency_on_exit(void* context) {
    App* app = (App*)context;
    Widget* widget = app->widget;
    widget_reset(widget);
};

// Handler Callback Lists
void (*const app_on_enter_handlers[])(void*) = {
    app_scene_select_mode_on_enter,
    app_scene_subghz_select_frequency_on_enter,
};
bool (*const app_on_event_handlers[])(void* context, SceneManagerEvent event) = {
    app_scene_select_mode_on_event,
    app_scene_subghz_select_frequency_on_event,
};
void (*const app_on_exit_handlers[])(void* context) = {
    app_scene_select_mode_on_exit,
    app_scene_subghz_select_frequency_on_exit,
};
const SceneManagerHandlers app_scene_handlers = {
    .on_enter_handlers = app_on_enter_handlers,
    .on_event_handlers = app_on_event_handlers,
    .on_exit_handlers = app_on_exit_handlers,
    .scene_num = AppSceneNum,
};

// View Dispatcher Callbacks
bool app_scene_custom_callback(void* context, uint32_t custom_event_id) {
    App* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event_id);
};
bool app_back_event_callback(void* context) {
    App* app = context;
    ;
    return scene_manager_handle_back_event(app->scene_manager);
}
// APP

App* app_alloc() {
    App* app = malloc(sizeof(App));
    app->frequency = 446.09375;

    app->scene_manager = scene_manager_alloc(&app_scene_handlers, app);

    // View Dispatcher
    app->view_dispatcher = view_dispatcher_alloc();
    view_dispatcher_enable_queue(app->view_dispatcher);
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(app->view_dispatcher, app_scene_custom_callback);
    view_dispatcher_set_navigation_event_callback(app->view_dispatcher, app_back_event_callback);
    // TextBox
    app->text_box = text_box_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, AppViewTextbox, text_box_get_view(app->text_box));
    // Widget
    app->widget = widget_alloc();
    view_dispatcher_add_view(app->view_dispatcher, AppViewWidget, widget_get_view(app->widget));
    return app;
};
void app_free(App* app) {
    view_dispatcher_remove_view(app->view_dispatcher, AppViewWidget);
    widget_free(app->widget);
    view_dispatcher_remove_view(app->view_dispatcher, AppViewTextbox);
    text_box_free(app->text_box);
    view_dispatcher_free(app->view_dispatcher);
    scene_manager_free(app->scene_manager);
    free(app);
};

int32_t cross_flipper_communication_app(void* p) {
    UNUSED(p);
    App* app = app_alloc();
    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, AppSceneSelectMode);
    view_dispatcher_run(app->view_dispatcher);

    app_free(app);
    furi_record_close(RECORD_GUI);
    return 0;
};
